In [1]:
# Import libraries
import pandas as pd

In [2]:
# Load the datasets
price_df = pd.read_csv(r"F:\HSE\Consulting Project\btc_analysis\btc_price_info.csv")
news_df = pd.read_csv(r"F:\HSE\Consulting Project\btc_analysis\news_btc_dataset.csv")

In [3]:
price_df

,date,price,opening_price,highest_price,lowest_price,volume,change
0,2025-04-15,84062,84587,86439,84048,59500,-0.62
1,2025-04-14,84586,83753,85795,83705,78030,1.02
2,2025-04-13,83734,85282,86000,83050,70930,-1.83
3,2025-04-12,85293,83420,85894,82828,55600,2.25
4,2025-04-11,83413,79606,84275,79004,94620,4.78
...,...,...,...,...,...,...,...
1195,2022-01-05,43426,45833,47019,42535,83740,-5.26
1196,2022-01-04,45837,46436,47505,45602,55590,-1.28
1197,2022-01-03,46430,47294,47556,45704,41060,-1.86
1198,2022-01-02,47312,47739,47945,46718,27020,-0.89
1199,2022-01-01,47738,46218,47918,46218,31240,3.29

In [4]:
news_df

,date,news_title,negative,positive,important,liked,disliked,lol,toxic,saved,comments,currency
0,2022-06-09,"TA: Bitcoin Stuck In Key Range, Why A Major Br...",1,0,0,0,0,0,0,0,0,BTC
1,2022-06-09,Bitcoin Trading Can Become Easier if You Follo...,0,0,0,0,0,0,0,1,0,BTC
2,2022-06-09,Gillibrand and Lummis state that most altcoins...,0,1,1,1,0,0,0,1,1,BTC
3,2022-06-08,U.S. Macro Pressure Responsible For Entire Bit...,2,1,0,1,3,1,0,0,0,BTC
4,2022-06-08,Shock And Awe: Bitcoin Lightning Network Capac...,0,1,1,1,0,0,0,0,0,BTC
...,...,...,...,...,...,...,...,...,...,...,...,...
22330,2024-10-03,"Latest data reveals global economic downturn, ...",0,0,0,0,0,0,0,0,0,BTC
22331,2024-10-02,Ten years of Bitcoin address data uncovers inv...,0,0,0,0,0,0,0,0,0,BTC
22332,2024-10-18,Behind Alchemy Pay and Yellow Cardâ€™s Bold Plan...,0,0,0,0,0,0,0,0,0,BTC
22333,2024-10-09,Alchemy Pay Expands Crypto Virtual Card to Sam...,0,0,0,0,0,0,0,0,0,BTC
22334,2024-09-25,Analysts remain divided on Q4 outlook despite ...,0,0,0,0,0,0,0,0,0,BTC

In [7]:
# Merge the datasets on 'date'
merged_btc = pd.merge(news_df, price_df, on='date', how='inner')

In [8]:
merged_btc

,date,news_title,negative,positive,important,liked,disliked,lol,toxic,saved,comments,currency,price,opening_price,highest_price,lowest_price,volume,change
0,2022-06-09,"TA: Bitcoin Stuck In Key Range, Why A Major Br...",1,0,0,0,0,0,0,0,0,BTC,30098,30202,30691,29954,61720,-0.34
1,2022-06-09,Bitcoin Trading Can Become Easier if You Follo...,0,0,0,0,0,0,0,1,0,BTC,30098,30202,30691,29954,61720,-0.34
2,2022-06-09,Gillibrand and Lummis state that most altcoins...,0,1,1,1,0,0,0,1,1,BTC,30098,30202,30691,29954,61720,-0.34
3,2022-06-09,LBank Exchange Will List Lego Coin (LEGO) on J...,0,0,0,0,0,0,0,0,0,BTC,30098,30202,30691,29954,61720,-0.34
4,2022-06-09,ITEMVERSE (ITEM) Is Now Available for Trading ...,0,0,0,0,0,0,0,0,0,BTC,30098,30202,30691,29954,61720,-0.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19736,2024-11-01,"Crypto Price Analysis 11-1 BITCOIN: BTC, ETHER...",0,0,0,0,0,0,0,0,0,BTC,69507,70279,71598,68846,130460,-1.10
19737,2024-11-01,Solana (SOL) Slides to Support: Bulls Ready to...,0,0,0,0,0,0,0,0,0,BTC,69507,70279,71598,68846,130460,-1.10
19738,2024-11-01,"Bitcoin Set To Gain If Trump Wins, JPMorgan Ci...",0,0,0,0,0,0,0,0,0,BTC,69507,70279,71598,68846,130460,-1.10
19739,2024-11-01,"Best Crypto to Buy Now November 1 â€“ Cardano, M...",0,0,0,0,0,0,0,0,0,BTC,69507,70279,71598,68846,130460,-1.10
19740,2024-11-01,Majority of Bitcoin metrics reveal bearish out...,0,0,0,0,0,0,0,0,0,BTC,69507,70279,71598,68846,130460,-1.10

In [9]:
# Save updated dataset in the local folder
merged_btc.to_csv(r"F:\HSE\Consulting Project\btc_analysis\merged_btc.csv", index=False, encoding='utf-8-sig')